---
networks:
  ldapNet:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}.0/24

services:
  openldap:
    image: johann8/alpine-openldap:${VERSION_OPENLDAP:-latest}
    container_name: openldap
    restart: unless-stopped
    environment:
      SLAPD_ROOTDN:            ${SLAPD_ROOTDN}
      SLAPD_ROOTPW:            ${SLAPD_ROOTPW}
      SLAPD_ROOTPW_HASH:       ${SLAPD_ROOTPW_HASH}
      SLAPD_ORGANIZATION:      ${SLAPD_ORGANIZATION}
      SLAPD_FQDN:              ${SLAPD_FQDN}
      SLAPD_SUFFIX:            ${SLAPD_SUFFIX}
      SLAPD_PWD_CHECK_QUALITY: ${SLAPD_PWD_CHECK_QUALITY}
      SLAPD_PWD_MIN_LENGTH:    ${SLAPD_PWD_MIN_LENGTH}
      SLAPD_PWD_MAX_FAILURE:   ${SLAPD_PWD_MAX_FAILURE}
      SLAPD_ROOTPW_SECRET:     ${SLAPD_ROOTPW_SECRET}
      SLAPD_USERPW_SECRET:     ${SLAPD_USERPW_SECRET}
      SLAPD_PASSWORD_HASH:     ${SLAPD_PASSWORD_HASH}
    hostname: ${HOSTNAME0}.${DOMAINNAME}
    volumes:
      - ${DOCKERDIR}/data/backup:/data/backup
      - ${DOCKERDIR}/data/prepopulate:/etc/openldap/prepopulate:ro
      - ${DOCKERDIR}/data/ldapdb:/var/lib/openldap/openldap-data
      - ${DOCKERDIR}/data/ssl:/etc/ssl/openldap
      - ${DOCKERDIR}/data/config/ldap/ldif:/etc/openldap/ldif:ro
      - ${DOCKERDIR}/data/config/ldap/slapd.d:/etc/openldap/slapd.d
      - ${DOCKERDIR}/data/config/ldap/custom-schema:/etc/openldap/custom-schema
      - ${DOCKERDIR}/data/config/ldap/secrets:/run/secrets
    ports:
      - ${PORT_LDAP:-389}:389
      - ${PORT_LDAPS:-636}:636
    networks:
      - ldapNet
    secrets:
      - ${SLAPD_ROOTPW_SECRET}
      - ${SLAPD_USERPW_SECRET}

  phpldapadmin:
    image: docker.io/phpldapadmin/phpldapadmin:${PLA_VERSION:-2.3.4}
    container_name: phpldapadmin
    restart: unless-stopped
    environment:
      ### === LDAP Configuration ===
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_NAME==${LDAP_NAME}
      - LDAP_PORT=${LDAP_PORT}
      - LDAP_CONNECTION=${LDAP_CONNECTION}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USERNAME=${LDAP_USERNAME}
      - LDAP_LOGIN_ATTR=${LDAP_LOGIN_ATTR}
      - LDAP_LOGIN_ATTR_DESC=${LDAP_LOGIN_ATTR_DESC}
      - LDAP_LOGIN_OBJECTCLASS=${LDAP_LOGIN_OBJECTCLASS}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - LDAP_ALLOW_GUEST=${LDAP_ALLOW_GUEST}
      - LDAP_ALERT_ROOTDN=${LDAP_ALERT_ROOTDN}
      - LDAP_CACHE=${LDAP_CACHE}

      ### === phpLDAPAdmin APP Configuration ===
      - APP_TIMEZONE=${APP_TIMEZONE}
      - APP_UPDATE_CHECK=${APP_UPDATE_CHECK}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}

      ### === Sonstige Configuration ===
      - LOG_CHANNEL=${LOG_CHANNEL}
      - CACHE_DRIVER=${CACHE_DRIVER}
      #- SESSION_DRIVER=${SESSION_DRIVER}
      #- SESSION_LIFETIME=${SESSION_LIFETIME}
      - LDAP_TEMPLATE_UIDNUMBER_START=${LDAP_TEMPLATE_UIDNUMBER_START}
      - LDAP_TEMPLATE_GIDNUMBER_START=${LDAP_TEMPLATE_GIDNUMBER_START}
    volumes:
      - ${DOCKERDIR}/data/pla2/sessions:/app/storage/framework/sessions
      - ${DOCKERDIR}/data/pla2/logs:/app/storage/logs
    #ports:
    #  - 7070:8080
    depends_on:
      openldap:
        condition: service_started
    networks:
      - ldapNet

secrets:
  openldap-root-password:
    file: ${DOCKERDIR}/data/config/ldap/secrets/${SLAPD_ROOTPW_SECRET}
  openldap-user-passwords:
    file: ${DOCKERDIR}/data/config/ldap/secrets/${SLAPD_USERPW_SECRET}
